# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartview" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/smartview"],
          writable_paths: ["{{staged_path}}/smartview"],
          must_succeed:   false
    end
  end

  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "7702ae2fe81ca1ae736bf3d689ea2882cfdb3320b1bc88ebc6aec0639d7d3cf8"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "06181fd256d6af56a43881e6712296602913fdf91f74afc615707b787afaae0f"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smartview"
  desc "Cross-platform terminal UI for monitoring drive health via smartmontools"
  homepage "https://github.com/trm42/smartview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "smartmontools",
    ]

  binary "smartview"

  # No zap stanza required
end
