# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartview" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "9de40a3aa1f7ce2d8c2ed5a60044c9209eb20d98dedb5dc1f7747bff528e0c08"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "f17bd1da04efb94bf8b5539d6a29ae9a9839132fe12fbfe097e5985856f143a8"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smartview"
  desc "Cross-platform terminal UI for monitoring drive health via smartmontools."
  homepage "https://github.com/trm42/smartview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "smartmontools",
    ]

  binary "smartview"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/smartview"],
          writable_paths: ["{{staged_path}}/smartview"],
          must_succeed:   false
    end
  end

  # No zap stanza required
end
