# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartview" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "{{staged_path}}/smartview"],
          writable_paths: ["{{staged_path}}/smartview"],
          must_succeed:   false
    end
  end

  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "50cd698ffa044016adfaeb65404a46fc601ee8fe24e6a4122744a3e43e381552"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "cbd25b8f82a1ac7b01a03b06f01e6393d81e6275a226b5bb7e451181a5c19fc7"
      url "https://github.com/trm42/smartview/releases/download/v#{version}/smartview_#{version}_linux_amd64.tar.gz"
    end
  end

  name "smartview"
  desc "Cross-platform terminal UI for monitoring drive health via smartmontools"
  homepage "https://github.com/trm42/smartview"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "smartmontools",
    ]

  binary "smartview"

  # No zap stanza required
end
